<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduKids.Comum\EduKids.Comum.csproj" />
    <ProjectReference Include="..\EduKids.Dominio\EduKids.Dominio.csproj" />
  </ItemGroup>

</Project>
